export const photos = [
  {
    alt: 'Trekking',
    src: './photos/IMG_2043.webp',
    original_path: './photos/IMG_2043.jpg',
    tags: ['Landscape', 'Europe'],
    time: [2022, 'July', ''],
    hv: true,
  },
  {
    alt: 'Melting Origin',
    src: './photos/IMG_2176.webp',
    original_path: './photos/IMG_2176.jpg',
    tags: ['Landscape', 'Europe'],
    time: [2022, 'July', ''],
    hv: true,
  },
  {
    alt: 'A sheep meh like cow',
    src: './photos/IMG_2214.webp',
    original_path: './photos/IMG_2214.jpg',
    tags: ['Animal', 'Europe'],
    time: [2022, 'July', ''],
    hv: false,
  },
  {
    alt: 'Oily Green',
    src: './photos/IMG_4493.webp',
    original_path: './photos/IMG_4493.jpg',
    tags: ['Phone', 'Green', 'Plants','San Francisco'],
    time: [2022, 'September', '24'],
    hv: true,
  },
  {
    alt: 'Fog',
    src: './photos/DSC00611.webp',
    original_path: './photos/DSC00611.jpg',
    tags: ['Street', 'Europe', 'B&W'],
    time: [2022, 'July', ''],
    hv: true,
  },
  
  {
    alt: 'Busy Train Station',
    src: './photos/IMG_1786.webp',
    original_path: './photos/IMG_1786.jpg',
    tags: ['Street', 'Europe'],
    time: [2022, 'July', ''],
    hv: true,
  },
  {
    alt: 'Man Playing Guitar',
    src: './photos/IMG_1780.webp',
    original_path: './photos/IMG_1780.webp',
    tags: ['Street', 'San Francisco'],
    time: [2022, '', ''],
    hv: true,
  },
  {
    alt: 'Sea Monster in Mall',
    src: './photos/IMG_3334.webp',
    original_path: './photos/IMG_3334.jpg',
    tags: ['Structure', 'Phone','Europe', 'B&W'],
    time: [2022, 'July', '27'],
    hv: false,
  },
  {
    alt: 'Watching Waterfall',
    src: './photos/IMG_3882.JPG',
    original_path: './photos/IMG_3882.JPG',
    tags: ['Animal', 'Europe', 'Phone'],
    time: [2022, 'Aug', '9'],
    hv: false,
  },
  {
    alt: 'Dorm Ceilling',
    src: './photos/IMG_4159.JPG',
    original_path: './photos/IMG_4159.JPG',
    tags: ['Stucture', 'Berkeley', 'Phone'],
    time: [2022, 'Aug', '22'],
    hv: false,
  },
  {
    alt: 'Woman in street market',
    src: './photos/IMG_1757.webp',
    original_path: './photos/IMG_1757.jpg',
    tags: ['Street', 'San Francisco'],
    time: [2022, '', ''],
    hv: true,
  },
  {
    alt: 'SF Downhill',
    src: './photos/IMG_1782.webp',
    original_path: './photos/IMG_1782.jpg',
    tags: ['Street', 'San Francisco'],
    time: [2022, '', ''],
    hv: true,
  },

  {
    alt: 'Clock Tower',
    src: './photos/DSC00689.webp',
    original_path: './photos/DSC00689.jpg',
    tags: ['Berkeley'],
    time: [2022, 'September', ''],
    hv: true,
  },
];

export let misc_tags = ['All', 'Phone'];
export let other_collapsible_tags = [
  {
    name: 'Location',
    collapsed: true,
    tags: ['Europe', 'San Francisco', 'Berkeley'],
  },
  {
    name: 'Form',
    collapsed: true,
    tags: ['Street', 'Landscape', 'Protrait', 'Structure'],
  },
  {
    name: 'Subject',
    collapsed: true,
    tags: ['Animal', 'Plants'],
  },
  {
    name: 'Color',
    collapsed: true,
    tags: ['B&W','Green'],
  },
];
