export const photos = [
  {
    alt: 'Trekking',
    src: './photos/IMG_2043.webp',
    original_path: '',
    tags: ['Landscape', 'Europe'],
    time: [2022, 'July', ''],
    hv: true,
  },
  {
    alt: 'Melting Origin',
    src: './photos/IMG_2176.webp',
    original_path: '',
    tags: ['Landscape', 'Europe'],
    time: [2022, 'July', ''],
    hv: true,
  },
  {
    alt: 'A sheep meh like cow',
    src: './photos/IMG_2214.webp',
    original_path: '',
    tags: ['Animal', 'Europe'],
    time: [2022, 'July', ''],
    hv: false,
  },
  {
    alt: 'Busy Train Station',
    src: './photos/IMG_1786.webp',
    original_path: '',
    tags: ['Street', 'Europe'],
    time: [2022, 'July', ''],
    hv: true,
  },
  {
    alt: 'Hollow Passage',
    src: './photos/IMG_1807.webp',
    original_path: '',
    tags: ['Structure', 'Europe','B&W'],
    time: [2022, '', ''],
    hv: true,
  },
  {
    alt: 'Woman in street market',
    src: './photos/IMG_1757.webp',
    original_path: '',
    tags: ['Street', 'San Francisco'],
    time: [2022, '', ''],
    hv: true,
  },
  {
    alt: 'Fog',
    src: './photos/DSC00611.webp',
    original_path: '',
    tags: ['Street', 'Europe', 'B&W'],
    time: [2022, 'July', ''],
    hv: true,
  },
  {
    alt: 'Man Playing Guitar',
    src: './photos/IMG_1780.webp',
    original_path: '',
    tags: ['Street', 'San Francisco'],
    time: [2022, '', ''],
    hv: true,
  },
  {
    alt: 'SF Downhill',
    src: './photos/IMG_1782.webp',
    original_path: '',
    tags: ['Street', 'San Francisco'],
    time: [2022, '', ''],
    hv: true,
  },
  {
    alt: 'White Flower',
    src: './photos/DSC00683.webp',
    original_path: '',
    tags: ['B&W', 'Berkeley'],
    time: [2022, '', ''],
    hv: true,
  },
  {
    alt: 'Man Playing Guitar',
    src: './photos/IMG_1751.webp',
    original_path: '',
    tags: ['Street', 'San Francisco'],
    time: [2022, '', ''],
    hv: false,
  },
  

];


export var all_tags = ["Animal", "Landscape", "Europe", "Street", "Structure", "San Francisco","Berkeley", "B&W", "All"];