export const photos = [
  {
    alt: 'Trekking',
    src: './photos/IMG_2043.webp',
    original_path: './photos/IMG_2043.jpg',
    tags: ['Landscape', 'Europe'],
    time: [2022, 'July', ''],
    hv: true,
    rating: 9,
  },
  {
    alt: 'Melting Origin',
    src: './photos/IMG_2176.webp',
    original_path: './photos/IMG_2176.jpg',
    tags: ['Landscape', 'Europe'],
    time: [2022, 'July', ''],
    hv: true,
    rating: 10,
  },
  {
    alt: 'A sheep meh like cow',
    src: './photos/IMG_2214.webp',
    original_path: './photos/IMG_2214.jpg',
    tags: ['Animal', 'Europe'],
    time: [2022, 'July', ''],
    hv: false,
    rating: 9,
  },
  {
    alt: 'Oily Green',
    src: './photos/IMG_4493.webp',
    original_path: './photos/IMG_4493.jpg',
    tags: ['Phone', 'Green', 'Plants', 'San Francisco'],
    time: [2022, 'September', '24'],
    hv: true,
    rating: 8,
  },
  {
    alt: 'Fog',
    src: './photos/DSC00611.webp',
    original_path: './photos/DSC00611.jpg',
    tags: ['Street', 'Europe', 'B&W'],
    time: [2022, 'July', ''],
    hv: true,
    rating: 5,
  },
  {
    alt: 'Busy Train Station',
    src: './photos/IMG_1786.webp',
    original_path: './photos/IMG_1786.jpg',
    tags: ['Street', 'Europe'],
    time: [2022, 'July', ''],
    hv: true,
    rating: 2,
  },
  {
    alt: 'Man Playing Guitar',
    src: './photos/IMG_1780.webp',
    original_path: './photos/IMG_1780.jpg',
    tags: ['Street', 'San Francisco'],
    time: [2022, '', ''],
    hv: true,
    rating: 7,
  },
  {
    alt: 'Sea Monster in Mall',
    src: './photos/IMG_3334.webp',
    original_path: './photos/IMG_3334.jpg',
    tags: ['Structure', 'Phone', 'Europe', 'B&W'],
    time: [2022, 'July', '27'],
    hv: false,
    rating: 8,
  },
  {
    alt: 'Watching Waterfall',
    src: './photos/IMG_3882.JPG',
    original_path: './photos/IMG_3882.JPG',
    tags: ['Animal', 'Europe', 'Phone'],
    time: [2022, 'Aug', '9'],
    hv: false,
    rating: 1,
  },
  {
    alt: 'Dorm Ceilling',
    src: './photos/IMG_4159.JPG',
    original_path: './photos/IMG_4159.JPG',
    tags: ['Stucture', 'Berkeley', 'Phone'],
    time: [2022, 'Aug', '22'],
    hv: true,
    rating: 3,
  },
  {
    alt: 'Woman in street market',
    src: './photos/IMG_1757.webp',
    original_path: './photos/IMG_1757.jpg',
    tags: ['Street', 'San Francisco'],
    time: [2022, '', ''],
    hv: true,
    rating: 1,
  },
  {
    alt: 'Clock Tower',
    src: './photos/DSC00689.webp',
    original_path: './photos/DSC00689.jpg',
    tags: ['Berkeley'],
    time: [2022, 'September', ''],
    hv: true,
    rating: 3,
  },
  {
    alt: 'Staff Charging',
    src: './photos/IMG_3333.webp',
    original_path: './photos/IMG_3333.jpg',
    tags: ['Phone', 'Structure', 'Europe'],
    time: ['2022', 'July', '27'],
    hv: false,
    rating: 7,
  },
  {
    alt: 'Picking Grocery',
    src: './photos/IMG_1506.webp',
    original_path: './photos/IMG_1506.jpg',
    tags: ['San Francisco', 'Street'],
    time: ['2022', 'May', '30'],
    hv: true,
    rating: 8,
  },
  {
    alt: 'SF City',
    src: './photos/IMG_9906.webp',
    original_path: './photos/IMG_9906.jpg',
    tags: ['Street', 'San Francisco', 'B&W'],
    time: ['2022', 'Jan', '26'],
    hv: true,
    rating: 8,
  },
  {
    alt: 'Revolution',
    src: './photos/IMG_7918.webp',
    original_path: './photos/IMG_7918.jpg',
    tags: ['Abstract', 'Purple'],
    time: ['2021', 'Aug', '18'],
    hv: true,
    rating: 5,
  },
  {
    alt: 'Fingerprint',
    src: './photos/IMG_7913.webp',
    original_path: './photos/IMG_7913.jpg',
    tags: ['Purple', 'Abstract'],
    time: ['2021', 'Aug', '19'],
    hv: true,
    rating: 5,
  },
  {
    alt: 'Radiance',
    src: './photos/IMG_9178.webp',
    original_path: './photos/IMG_9178.jpg',
    tags: ['San Francisco'],
    time: ['2021', 'Nov', '27'],
    hv: false,
    rating: 7,
  },
  {
    alt: 'Applause',
    src: './photos/IMG_9063.webp',
    original_path: './photos/IMG_9063.jpg',
    tags: ['San Francisco'],
    time: ['2021', 'Oct', '25'],
    hv: true,
    rating: 7,
  },
  {
    alt: 'Man with Flower',
    src: './photos/IMG_0690_1.webp',
    original_path: './photos/IMG_0690_1.jpg',
    tags: ['Street', 'Protrait'],
    time: ['2022', 'March', '2'],
    hv: true,
    rating: 7,
  },
  {
    alt: 'Banquet on Island',
    src: './photos/IMG_0976.webp',
    original_path: './photos/IMG_0976.jpg',
    tags: ['Plants', 'Green', 'San Francisco', 'Landscape'],
    time: ['2022', 'May', '9'],
    hv: true,
    rating: 8,
  },
  {
    alt: 'Sinking',
    src: './photos/seashore.webp',
    original_path: './photos/seashore.jpg',
    tags: ['Purple', 'Landscape'],
    time: ['2022', 'April', '25'],
    hv: true,
    rating: 8,
  },
  {
    alt: 'Trapped when Falling',
    src: './photos/bigger.webp',
    original_path: './photos/bigger.jpg',
    tags: ['Purple', 'Plants'],
    time: ['2021', 'June', '4'],
    hv: true,
    rating: 5,
  },
  {
    alt: 'Sandwich',
    src: './photos/IMG_0857.jpg',
    original_path: './photos/IMG_0857.webp',
    tags: ['San Francisco', 'Street'],
    time: ['2022', 'May', '4'],
    hv: false,
    rating: 7,
  },
  {
    alt: 'Buy this!',
    src: './photos/IMG_1378.jpg',
    original_path: './photos/IMG_1378.webp',
    tags: ['Street'],
    time: ['2022', 'May', '28'],
    hv: true,
    rating: 6,
  },
  //add here
];

export let misc_tags = ['All', 'Phone'];
export let other_collapsible_tags = [
  {
    name: 'Location',
    collapsed: true,
    tags: ['Europe', 'San Francisco', 'Berkeley'],
  },
  {
    name: 'Form',
    collapsed: true,
    tags: ['Street', 'Landscape', 'Protrait', 'Structure','Abstract'],
  },
  {
    name: 'Subject',
    collapsed: true,
    tags: ['Animal', 'Plants'],
  },
  {
    name: 'Color',
    collapsed: true,
    tags: ['B&W', 'Green', 'Purple', 'Blue'],
  },
];
